import { useForm, usePage } from '@inertiajs/react';
import { AlertOctagon, Eye, EyeOff, Key, Server } from 'lucide-react';
import { useState } from 'react';
import SystemConfigController from '@/actions/App/Http/Controllers/SystemConfigController';
import { Toggle } from '@/components/system-config/toggle';

export type MlServerSettings = {
    ml_server_name: string | null;
    ml_server_url: string | null;
    ml_admin_key: string | null;
    ml_description: string | null;
    ml_is_active: boolean;
};

export function MlServerConfigForm({
    settings,
}: {
    settings: MlServerSettings;
}) {
    const { data, setData, post, processing, errors } = useForm({
        ml_server_name: settings?.ml_server_name ?? '',
        ml_description: settings?.ml_description ?? '',
        ml_is_active: settings?.ml_is_active ?? true,
    });

    const [showMlAdminKey, setShowMlAdminKey] = useState(false);
    const { auth } = usePage<{ auth: { token: string | null } }>().props;

    const submit = (e: React.FormEvent) => {
        e.preventDefault();
        post(SystemConfigController.updateMl.url(), {
            headers: auth.token ? { Authorization: `Bearer ${auth.token}` } : {},
        });
    };

    return (
        <form
            onSubmit={submit}
            className="rounded-xl border border-gray-200 bg-white p-6 shadow-sm"
        >
            <div className="mb-1 flex items-center gap-2">
                <AlertOctagon className="h-5 w-5 text-gray-500" />
                <h2
                    className="text-base font-semibold"
                    style={{ color: '#0d1b2a' }}
                >
                    ML Server Configuration
                </h2>
            </div>
            <div className="mb-5 h-px" style={{ backgroundColor: '#f5a623' }} />

            {/* ML Server Name */}
            <div className="mb-4">
                <label className="mb-1.5 block text-[11px] font-semibold tracking-widest text-gray-400 uppercase">
                    ML Server Name
                </label>
                <input
                    type="text"
                    value={data.ml_server_name}
                    onChange={(e) => setData('ml_server_name', e.target.value)}
                    placeholder="My ML Server"
                    className="w-full rounded-lg border border-gray-200 px-3 py-2.5 text-sm text-gray-700 placeholder-gray-300 outline-none"
                />
                {errors.ml_server_name && (
                    <p className="mt-1 text-xs text-red-500">
                        {errors.ml_server_name}
                    </p>
                )}
            </div>

            {/* ML Server URL — fixed via ML_AUTH_BASE_URL env config, not editable here */}
            <div className="mb-4">
                <label className="mb-1.5 block text-[11px] font-semibold tracking-widest text-gray-400 uppercase">
                    <Server className="mr-1 inline h-3 w-3" />
                    ML Server URL
                </label>
                <input
                    type="text"
                    value={settings?.ml_server_url ?? ''}
                    readOnly
                    placeholder="Configured via ML_AUTH_BASE_URL"
                    className="w-full rounded-lg border border-gray-200 bg-gray-50 px-3 py-2.5 text-sm text-gray-700 placeholder-gray-300 outline-none"
                />
            </div>

            {/* ML Admin Key — generated by the server, not typed in */}
            <div className="mb-4">
                <label className="mb-1.5 block text-[11px] font-semibold tracking-widest text-gray-400 uppercase">
                    <Key className="mr-1 inline h-3 w-3" />
                    ML Admin Key
                </label>
                {settings?.ml_admin_key ? (
                    <div className="flex items-center gap-2">
                        <input
                            type={showMlAdminKey ? 'text' : 'password'}
                            value={settings.ml_admin_key}
                            readOnly
                            className="flex-1 rounded-lg border border-gray-200 bg-gray-50 px-3 py-2.5 text-sm text-gray-700 outline-none"
                        />
                        <button
                            type="button"
                            onClick={() => setShowMlAdminKey((v) => !v)}
                            className="rounded-lg border border-gray-200 p-2.5 text-gray-400 transition-colors hover:bg-gray-50 hover:text-gray-600"
                        >
                            {showMlAdminKey ? (
                                <EyeOff className="h-4 w-4" />
                            ) : (
                                <Eye className="h-4 w-4" />
                            )}
                        </button>
                    </div>
                ) : (
                    <p className="text-xs text-gray-400">
                        Not created yet — saving this form will create an admin key on the ML server. This unlocks token generation/assignment for beekeepers.
                    </p>
                )}
            </div>

            {/* ML Description */}
            <div className="mb-4">
                <label className="mb-1.5 block text-[11px] font-semibold tracking-widest text-gray-400 uppercase">
                    Description
                </label>
                <textarea
                    value={data.ml_description}
                    onChange={(e) => setData('ml_description', e.target.value)}
                    placeholder="Description of this ML server"
                    className="w-full rounded-lg border border-gray-200 px-3 py-2.5 text-sm text-gray-700 placeholder-gray-300 outline-none"
                    rows={3}
                />
                {errors.ml_description && (
                    <p className="mt-1 text-xs text-red-500">
                        {errors.ml_description}
                    </p>
                )}
            </div>

            {/* ML Is Active */}
            <div className="mb-5">
                <label className="mb-1.5 block text-[11px] font-semibold tracking-widest text-gray-400 uppercase">
                    Is Active
                </label>
                <Toggle
                    on={data.ml_is_active}
                    onChange={() => setData('ml_is_active', !data.ml_is_active)}
                />
            </div>

            <button
                type="submit"
                disabled={processing}
                className="w-full rounded-xl py-2.5 text-sm font-bold transition-opacity hover:opacity-90 disabled:opacity-60"
                style={{ backgroundColor: '#f5a623', color: '#0d1b2a' }}
            >
                {processing ? 'Saving…' : 'Save ML Server Settings'}
            </button>
        </form>
    );
}
